services:

  https-portal:
    environment:
      DOMAINS: >
        mailcatcher.kcm.test -> http://mailcatcher:1080,
        phpredisadmin.kcm.test -> http://phpredisadmin:80,
        ${HTTPS_PORTAL_SITES}
    depends_on:
      - mailcatcher

  php:
    image: kcm-php-dev
    build:
      dockerfile: Dockerfile.php.dev

  phpmyadmin:
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}

  mailcatcher:
    image: stpaquet/alpinemailcatcher:${MAILCATCHER_VERSION:-latest}

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:${PHPREDISADMIN_VERSION:-latest}
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_NAME=kcm
      - REDIS_1_PORT=6379
    expose:
      - 80
    depends_on:
      - redis
